<a href="https://colab.research.google.com/github/supperglossar/Mathematocal_Foundations/blob/main/content/algebra/les03_labo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Labo - Matrixvermenigvuldiging

**Mathematical Foundations - IT & Artificial Intelligence**

---

In dit labo oefen je met matrixvermenigvuldiging, lineaire transformaties en het bouwen van netwerklagen. De oefeningen bouwen voort op de theorie en bereiden je voor op het implementeren van echte neurale netwerken.

In [1]:
# Voer deze cel eerst uit om alle benodigde libraries te importeren

import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import fetch_openml

np.set_printoptions(precision=3, suppress=True)

# Laad MNIST
print("MNIST laden...")
mnist = fetch_openml('mnist_784', version=1, as_frame=False)
X, y = mnist.data, mnist.target.astype(int)
print(f"Geladen: {len(X)} afbeeldingen")

MNIST laden...
Geladen: 70000 afbeeldingen


---

## Oefening 1: Matrices Aanmaken


### Opdracht 1a

Maak de volgende matrices aan met NumPy functies:

1. Een 3×4 matrix gevuld met nullen
2. Een 2×5 matrix gevuld met enen
3. Een 4×4 identiteitsmatrix
4. Een 3×3 diagonaalmatrix met waarden [2, 5, 7] op de diagonaal
5. Een 3×4 matrix met random waarden uit een normale verdeling

In [2]:
# Jouw code voor opdracht 1a:

# 1. Een 3x4 matrix gevuld met nullen
matrix_zeros = np.zeros((3, 4))
print("3x4 matrix met nullen:")
print(matrix_zeros)
print()

# 2. Een 2x5 matrix gevuld met enen
matrix_ones = np.ones((2, 5))
print("2x5 matrix met enen:")
print(matrix_ones)
print()

# 3. Een 4x4 identiteitsmatrix
identity_matrix = np.eye(4)
print("4x4 identiteitsmatrix:")
print(identity_matrix)
print()

# 4. Een 3x3 diagonaalmatrix met waarden [2, 5, 7] op de diagonaal
diagonal_matrix = np.diag([2, 5, 7])
print("3x3 diagonaalmatrix met [2, 5, 7]:")
print(diagonal_matrix)
print()

# 5. Een 3x4 matrix met random waarden uit een normale verdeling
random_matrix = np.random.randn(3, 4)
print("3x4 matrix met random waarden (normale verdeling):")
print(random_matrix)
print()

3x4 matrix met nullen:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

2x5 matrix met enen:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

4x4 identiteitsmatrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

3x3 diagonaalmatrix met [2, 5, 7]:
[[2 0 0]
 [0 5 0]
 [0 0 7]]

3x4 matrix met random waarden (normale verdeling):
[[-1.133 -1.407  0.436  1.308]
 [-0.522  0.624  0.479 -0.187]
 [-0.105 -0.197  0.841  1.324]]



### Opdracht 1b

Gegeven de vector `v = np.arange(12)` (getallen 0-11), reshape deze naar:

1. Een 3×4 matrix
2. Een 4×3 matrix
3. Een 2×6 matrix
4. Een 2×2×3 tensor (3D)

Print elke keer de shape en de matrix zelf.

In [3]:
v = np.arange(12)
print(f"Originele vector: {v}\n")

# Jouw code voor opdracht 1b:

# Matrix een
matrix_een = v.reshape(3, 4)
print("3x4 matrix:")
print(matrix_een)
print()

# Matrix twee
matrix_twee = v.reshape(4, 3)
print("4x3 matrix:")
print(matrix_twee)
print()

# Matrix drie
matrix_drie = v.reshape(2, 6)
print("2x6 matrix:")
print(matrix_drie)
print

# Matrix vier
matrix_vier = v.reshape(2, 2, 3)
print("2x2x3 tensor:")
print(matrix_vier)

Originele vector: [ 0  1  2  3  4  5  6  7  8  9 10 11]

3x4 matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

4x3 matrix:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

2x6 matrix:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
2x2x3 tensor:
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


---

## Oefening 2: Matrixvermenigvuldiging


### Opdracht 2a

Gegeven de matrices:
```
A = [[1, 2],      B = [[5, 6],
     [3, 4]]           [7, 8]]
```

Bereken met de hand (op papier of in commentaar) én met NumPy:
1. A @ B
2. B @ A
3. Verifieer dat A @ B ≠ B @ A

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Jouw code voor opdracht 2a:

# A @ B
product_AB = A @ B
print("A @ B:")
print(product_AB)
print()

# B @ A
product_BA = B @ A
print("B @ A:")
print(product_BA)
print()

# A @ B ≠ B @ A
product_AB_equals_BA = np.array_equal(product_AB, product_BA)
print("A @ B = B @ A? ", product_AB_equals_BA)


A @ B:
[[19 22]
 [43 50]]

B @ A:
[[23 34]
 [31 46]]

A @ B = B @ A?  False


### Opdracht 2b

Bepaal voor elk van de volgende matrixparen of het product gedefinieerd is. Zo ja, bereken het product en geef de shape. Zo nee, leg uit waarom niet.

1. (3×2) @ (2×4)
2. (2×3) @ (2×3)
3. (4×1) @ (1×3)
4. (5×3) @ (3×5)
5. (2×2) @ (2×2) @ (2×2)

In [10]:
from numpy._core.fromnumeric import prod
# Jouw code voor opdracht 2b:

# Product een
product_een = np.dot(np.random.rand(3, 2), np.random.rand(2, 4))
print("Product een:")
print(product_een)
print("Shape:", product_een.shape)
print()

# product twee
print("Product twee:")
print("Is niet gedefinieerd!")
print("Omdat het aantal kolommen van matrix A niet gelijk is aan het aantal rijen van matrix B.")
print()

# Product drie
product_drie = np.dot(np.random.rand(4, 1), np.random.rand(1, 3))
print("Product drie:")
print(product_drie)
print("Shape:", product_drie.shape)
print()

# Product vier
product_vier = np.dot(np.random.rand(5, 3), np.random.rand(3,5))
print("Product vier:")
print(product_vier)
print("Shape:", product_vier.shape)
print()

# Product vijf
product_vijf = np.dot(np.random.rand(2, 2), np.random.rand(2, 2), np.random.rand(2, 2))
print("Product vijf:")
print(product_vijf)
print("Shape:", product_vijf.shape)
print()


Product een:
[[0.241 0.397 0.359 0.179]
 [0.123 0.166 0.204 0.103]
 [0.296 0.412 0.481 0.242]]
Shape: (3, 4)

Product twee:
Is niet gedefinieerd!
Omdat het aantal kolommen van matrix A niet gelijk is aan het aantal rijen van matrix B.

Product drie:
[[0.094 0.186 0.261]
 [0.014 0.027 0.038]
 [0.09  0.178 0.251]
 [0.065 0.127 0.179]]
Shape: (4, 3)

Product vier:
[[0.202 0.323 0.601 0.832 0.478]
 [0.21  0.758 0.718 0.952 0.401]
 [0.766 1.018 0.322 0.789 0.855]
 [0.634 1.18  1.123 1.674 1.042]
 [0.434 0.81  0.386 0.681 0.511]]
Shape: (5, 5)

Product vijf:
[[0.532 0.238]
 [1.201 0.873]]
Shape: (2, 2)



### Opdracht 2c

Verifieer de associativiteit van matrixvermenigvuldiging: (A @ B) @ C = A @ (B @ C).

Maak drie willekeurige matrices A (2×3), B (3×4) en C (4×2) en toon dat beide zijden gelijk zijn.

In [15]:
# Jouw code voor opdracht 2c:

# Matrix A
A = np.random.rand(2, 3)
print("Matrix A:")
print(A)

# Matrix B
B = np.random.rand(3, 4)
print("\nMatrix B:")
print(B)

# Matrix C
C = np.random.rand(4, 2)
print("\nMatrix C:")
print(C)

# Matrixvermenigvuldiging
left_side = np.dot(np.dot(A, B), C)
right_side = np.dot(A, np.dot(B, C))

# Checken of beide zijden gelijk zijn
are_equal = np.array_equal(left_side, right_side)

# Associatief
print("\nIs (A @ B) @ C = A @ (B @ C)?", are_equal)
print()

Matrix A:
[[0.102 0.508 0.014]
 [0.359 0.989 0.746]]

Matrix B:
[[0.317 0.977 0.777 0.518]
 [0.242 0.86  0.648 0.344]
 [0.616 0.26  0.853 0.735]]

Matrix C:
[[0.013 0.297]
 [0.975 0.521]
 [0.947 0.201]
 [0.271 0.55 ]]

Is (A @ B) @ C = A @ (B @ C)? True



---

## Oefening 3: Netwerklaag Implementeren


### Opdracht 3a

Implementeer een `Layer` class met:
- Een `__init__` methode die `input_size` en `output_size` accepteert en gewichten W en biases b initialiseert
- Een `forward` methode die de output berekent: X @ W + b
- Een `__repr__` methode die de layer beschrijft

Initialiseer gewichten met random waarden (schaal: 0.01) en biases met nullen.

In [ ]:
# Jouw code voor opdracht 3a:

class Layer:
    pass  # Vervang dit met je implementatie


# Test je implementatie:
# layer = Layer(784, 128)
# print(layer)
# output = layer.forward(X[:5])  # 5 MNIST afbeeldingen
# print(f"Output shape: {output.shape}")

### Opdracht 3b

Breid je Layer class uit met een activatiefunctie. Voeg een parameter `activation` toe aan `__init__` die kan zijn: 'none', 'relu', of 'sigmoid'. Pas de gekozen activatie toe in de forward methode.

ReLU: max(0, x)
Sigmoid: 1 / (1 + e^(-x))

In [ ]:
# Jouw code voor opdracht 3b:



### Opdracht 3c

Bouw een volledig netwerk door meerdere layers te combineren:
- Input: 784
- Hidden 1: 256 (ReLU)
- Hidden 2: 128 (ReLU)
- Output: 10 (geen activatie, of softmax als bonus)

Schrijf een functie `forward_network(X, layers)` die de input door alle layers stuurt. Test met een batch van 10 MNIST afbeeldingen.

In [ ]:
# Jouw code voor opdracht 3c:



---

## Oefening 4: Batch Processing


### Opdracht 4a

Neem de eerste 1000 MNIST afbeeldingen en verdeel ze in batches van 32. Hoeveel volledige batches krijg je? Wat doe je met de overgebleven afbeeldingen?

In [ ]:
# Jouw code voor opdracht 4a:



### Opdracht 4b

Schrijf een functie `create_batches(X, batch_size)` die een dataset X opdeelt in batches. De functie moet een lijst van batches teruggeven. Als de laatste batch kleiner is dan batch_size, neem deze toch mee.

Test met X[:100] en batch_size=32.

In [ ]:
# Jouw code voor opdracht 4b:



### Opdracht 4c

Meet de tijd om 1000 afbeeldingen te verwerken door een layer op twee manieren:
1. Eén voor één (for loop)
2. Als batches van 100

Gebruik `time.time()` om de tijd te meten. Welke methode is sneller?

In [ ]:
import time

# Jouw code voor opdracht 4c:



---

## Oefening 5: 2D Transformaties Visualiseren


### Opdracht 5a

Maak transformatiematrices voor de volgende operaties:
1. Schaling: vergroot x met factor 2, vergroot y met factor 0.5
2. Rotatie: 90 graden tegen de klok in
3. Reflectie: spiegel over de lijn y = x
4. Shear: verschuif y proportioneel met x (factor 0.5)

Druk elke matrix af.

In [ ]:
# Jouw code voor opdracht 5a:



### Opdracht 5b

Visualiseer het effect van elke transformatie uit 5a op een eenheidsvierkant (hoekpunten: (0,0), (1,0), (1,1), (0,1)). Maak een figuur met 4 subplots, één voor elke transformatie. Toon het originele vierkant in blauw en het getransformeerde in rood.

In [ ]:
# Jouw code voor opdracht 5b:



### Opdracht 5c

Combineer transformaties: maak een matrix die eerst roteert met 45 graden en dan schaalt met factor 1.5. Vergelijk het resultaat van de samengestelde matrix met het stapsgewijs toepassen van de transformaties. Visualiseer beide resultaten.

In [ ]:
# Jouw code voor opdracht 5c:



---

## Oefening 6: Mini-Netwerk Bouwen


### Opdracht 6a

Bouw een compleet mini-netwerk class met:
- Architectuur: 784 → 128 → 10
- ReLU na de eerste laag
- Softmax na de tweede laag
- Een `forward` methode
- Een `predict` methode die de klasse met hoogste kans teruggeeft
- Een methode `count_parameters` die het totaal aantal parameters telt

In [ ]:
# Jouw code voor opdracht 6a:



### Opdracht 6b

Test je netwerk op 100 MNIST afbeeldingen. Bereken de "accuracy" (percentage correcte voorspellingen). Met random gewichten verwacht je ongeveer 10% (random gokken tussen 10 klassen).

In [ ]:
# Jouw code voor opdracht 6b:



---

## Oefening 7: Transpose Eigenschappen


### Opdracht 7a

Verifieer de volgende transpose eigenschappen met willekeurige matrices:

1. (Aᵀ)ᵀ = A
2. (A + B)ᵀ = Aᵀ + Bᵀ
3. (cA)ᵀ = c(Aᵀ) voor scalar c
4. (A @ B)ᵀ = Bᵀ @ Aᵀ

In [ ]:
# Jouw code voor opdracht 7a:



### Opdracht 7b

Een matrix A is symmetrisch als A = Aᵀ. Toon aan dat voor elke matrix M geldt dat M @ Mᵀ altijd symmetrisch is. Verifieer dit met een willekeurige 3×5 matrix.

In [ ]:
# Jouw code voor opdracht 7b:



---

## Klaar!

Je hebt de labo-oefeningen van les 3 afgerond. Je kunt nu matrixvermenigvuldiging toepassen om complete netwerklagen te berekenen en begrijpt hoe lineaire transformaties werken.

In de volgende les leren we over de inverse matrix en het oplossen van stelsels vergelijkingen.