<a href="https://colab.research.google.com/github/supperglossar/Mathematocal_Foundations/blob/main/content/algebra/les04_labo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Labo: Stelsels en de Inverse Matrix

**Mathematical Foundations - IT & Artificial Intelligence**

---

In dit labo oefen je met stelsels van vergelijkingen, de inverse matrix, determinanten en lineaire regressie. Dit is de laatste les van het lineaire algebra blok.

In [1]:
import numpy as np
import matplotlib.pyplot as plt

np.set_printoptions(precision=4, suppress=True)
print("Libraries geladen!")

Libraries geladen!


---

## Oefening 1: Stelsels Opstellen


### Opdracht 1a

Vertaal de volgende woordproblemen naar matrixvorm Ax = b:

**Probleem 1:** Een winkel verkoopt appels en peren. 3 appels en 2 peren kosten €5. 1 appel en 4 peren kosten €6. Wat is de prijs per appel en per peer?

**Probleem 2:** Een trein rijdt van A naar B. Met de wind mee (snelheid + wind) doet hij er 2 uur over voor 300 km. Tegen de wind in (snelheid - wind) doet hij er 3 uur over voor dezelfde afstand. Wat is de snelheid van de trein en de windsnelheid?

In [4]:
# Jouw code voor opdracht 1a:

# Probleem 1: appels (a) en peren (p)
# 3a + 2p = 5
# 1a + 4p = 6


# Probleem 2: snelheid (s) en wind (w)
# (s + w) * 2 = 300  →  2s + 2w = 300
# (s - w) * 3 = 300  →  3s - 3w = 300

A = np.array([[3, 2],
              [1, 4]])
b = np.array([5, 6])

print("Stelsel van probleem 1:")
print("  3a + 2p = 5")
print("  1a + 4p = 6")
print()
print("In matrixvorm Ax = b:")
print(f"A = \n{A}")
print(f"b = {b}")
print()
print("We zoeken x = [x, y] zodat A @ x = b")

S = np.array([[2, 2],
              [3, 3]])
w = np.array([300, 300])

print("Stelsel van probleem 2:")
print("  2s + 2w = 300")
print("  3s - 3w = 300")
print()
print("In matrixvorm Ax = b:")
print(f"A = \n{S}")
print(f"b = {w}")
print()
print("We zoeken x = [x, y] zodat A @ x = b")


Stelsel van probleem 1:
  3a + 2p = 5
  1a + 4p = 6

In matrixvorm Ax = b:
A = 
[[3 2]
 [1 4]]
b = [5 6]

We zoeken x = [x, y] zodat A @ x = b
Stelsel van probleem 2:
  2s + 2w = 300
  3s - 3w = 300

In matrixvorm Ax = b:
A = 
[[2 2]
 [3 3]]
b = [300 300]

We zoeken x = [x, y] zodat A @ x = b


### Opdracht 1b

Los beide stelsels op met `np.linalg.solve()` en interpreteer de antwoorden.

In [9]:
# Jouw code voor opdracht 1b:

# Oplossen met NumPy
x_oplossing = np.linalg.solve(A, b)

print(f"Oplossing 1: x = {x_oplossing}")
print(f"  x = {x_oplossing[0]}")
print(f"  y = {x_oplossing[1]}")
print()

# Verificatie
print("Verificatie (A @ x moet gelijk zijn aan b):")
print(f"  A @ x = {A @ x_oplossing}")
print(f"  b     = {b}")
print(f"  Gelijk? {np.allclose(A @ x_oplossing, b)}")



Oplossing 1: x = [0.8 1.3]
  x = 0.7999999999999999
  y = 1.3

Verificatie (A @ x moet gelijk zijn aan b):
  A @ x = [5. 6.]
  b     = [5 6]
  Gelijk? True


### Opdracht 1c

Stel het volgende 3×3 stelsel op en los het op:

Een bakker maakt 3 soorten brood. Tarwebrood kost €2, roggebrood €3, en meergranenbrood €4. Op maandag verkoopt hij 10 tarwe, 5 rogge en 8 meergranen voor €67. Op dinsdag verkoopt hij 8 tarwe, 10 rogge en 6 meergranen voor €70. Op woensdag verkoopt hij 12 tarwe, 8 rogge en 10 meergranen voor €88.

Verifieer dat de gegeven prijzen kloppen door het stelsel op te lossen.

In [10]:
# Jouw code voor opdracht 1c:

# Een groter stelsel: 3 vergelijkingen, 3 onbekenden
# 20 + 15 + 32 = 67
# 16 + 20 + 24 = 70
# 24 + 24 + 30 = 88

A3 = np.array([
    [20, 15, 32],
    [16, 20, 24],
    [24, 24, 30]
])

b3 = np.array([67, 70, 88])

x3 = np.linalg.solve(A3, b3)

print("Stelsel:")
print(" 20 + 15 + 32 = 67")
print(" 16 + 20 + 24 = 70")
print(" 24 + 24 + 30 = 88")
print()
print(f"Oplossing: x = {x3[0]:.4f}, y = {x3[1]:.4f}, z = {x3[2]:.4f}")
print()
print(f"Verificatie: A @ x = {A3 @ x3}")
print(f"            b     = {b3}")

Stelsel:
 20 + 15 + 32 = 67
 16 + 20 + 24 = 70
 24 + 24 + 30 = 88

Oplossing: x = 0.6701, y = 2.1806, z = 0.6528

Verificatie: A @ x = [67. 70. 88.]
            b     = [67 70 88]


---

## Oefening 2: Stelsels Oplossen


### Opdracht 2a

Los de volgende stelsels op en verifieer je antwoord door A @ x te berekenen:

**Stelsel 1:**
```
2x + y = 5
x - y = 1
```

**Stelsel 2:**
```
x + y + z = 6
2x - y + z = 3
x + 2y - z = 3
```

In [11]:
# Jouw code voor opdracht 2a:

# Stelsel 1:
# 2x + y = 5
# x - y = 1
A1 = np.array([[2, 1],
               [1, -1]])
b1 = np.array([5, 1])

x1_solution = np.linalg.solve(A1, b1)

print(f"Oplossing voor Stelsel 1: x = {x1_solution}")
print(f"  x = {x1_solution[0]:.2f}")
print(f"  y = {x1_solution[1]:.2f}")

# Verificatie
print("Verificatie (A @ x moet gelijk zijn aan b):")
print(f"  A @ x = {A1 @ x1_solution}")
print(f"  b     = {b1}")
print(f"  Gelijk? {np.allclose(A1 @ x1_solution, b1)}")

# Stelsel 2:
# x + y + z = 6
# 2x - y + z = 3
# x + 2y - z = 3
A2 = np.array([[1, 1, 1],
               [2, -1, 1],
               [1, 2, -1]])
b2 = np.array([6, 3, 3])

x2_solution = np.linalg.solve(A2, b2)

print(f"\nOplossing voor Stelsel 2: x = {x2_solution}")
print(f"  x = {x2_solution[0]:.2f}")
print(f"  y = {x2_solution[1]:.2f}")
print(f"  z = {x2_solution[2]:.2f}")

# Verificatie
print("Verificatie (A @ x moet gelijk zijn aan b):")
print(f"  A @ x = {A2 @ x2_solution}")
print(f"  b     = {b2}")
print(f"  Gelijk? {np.allclose(A2 @ x2_solution, b2)}")

Oplossing voor Stelsel 1: x = [2. 1.]
  x = 2.00
  y = 1.00
Verificatie (A @ x moet gelijk zijn aan b):
  A @ x = [5. 1.]
  b     = [5 1]
  Gelijk? True

Oplossing voor Stelsel 2: x = [1.2857 2.1429 2.5714]
  x = 1.29
  y = 2.14
  z = 2.57
Verificatie (A @ x moet gelijk zijn aan b):
  A @ x = [6. 3. 3.]
  b     = [6 3 3]
  Gelijk? True


### Opdracht 2b

Wat gebeurt er als je probeert het volgende stelsel op te lossen?

```
x + 2y = 3
2x + 4y = 6
```

Leg uit waarom dit stelsel oneindig veel oplossingen heeft.

In [12]:
# Jouw code voor opdracht 2b:

A_inf = np.array([[1, 2],
                  [2, 4]])
b_inf = np.array([3, 6])

print("Matrix A:")
print(A_inf)
print("Vector b:")
print(b_inf)

determinant_inf = np.linalg.det(A_inf)
print(f"De determinant van A is: {determinant_inf}")

print("\nDit stelsel heeft oneindig veel oplossingen omdat de tweede vergelijking een veelvoud is van de eerste vergelijking.")
print("2 * (x + 2y) = 2 * 3  wordt  2x + 4y = 6.")
print("Beide vergelijkingen stellen dezelfde lijn voor in een 2D-vlak, dus elk punt op die lijn is een oplossing.")
print("Een determinant van 0 bevestigt dat de matrix singulier is en dus niet uniek oplosbaar (of geen oplossing, of oneindig veel).")

try:
    x_inf = np.linalg.solve(A_inf, b_inf)
    print(f"Oplossing: {x_inf}")
except np.linalg.LinAlgError as e:
    print(f"\nFout bij het oplossen van het stelsel met np.linalg.solve(): {e}")
    print("Dit bevestigt dat de matrix singulier is en niet uniek oplosbaar.")


Matrix A:
[[1 2]
 [2 4]]
Vector b:
[3 6]
De determinant van A is: 0.0

Dit stelsel heeft oneindig veel oplossingen omdat de tweede vergelijking een veelvoud is van de eerste vergelijking.
2 * (x + 2y) = 2 * 3  wordt  2x + 4y = 6.
Beide vergelijkingen stellen dezelfde lijn voor in een 2D-vlak, dus elk punt op die lijn is een oplossing.
Een determinant van 0 bevestigt dat de matrix singulier is en dus niet uniek oplosbaar (of geen oplossing, of oneindig veel).

Fout bij het oplossen van het stelsel met np.linalg.solve(): Singular matrix
Dit bevestigt dat de matrix singulier is en niet uniek oplosbaar.


### Opdracht 2c

Wat gebeurt er als je probeert het volgende stelsel op te lossen?

```
x + 2y = 3
2x + 4y = 8
```

Leg uit waarom dit stelsel geen oplossing heeft.

In [13]:
# Jouw code voor opdracht 2c:

A_no_sol = np.array([[1, 2],
                     [2, 4]])
b_no_sol = np.array([3, 8])

print("Matrix A:")
print(A_no_sol)
print("Vector b:")
print(b_no_sol)

determinant_no_sol = np.linalg.det(A_no_sol)
print(f"De determinant van A is: {determinant_no_sol}")

print("\nDit stelsel heeft geen oplossing. Hoewel de linkerzijde van de tweede vergelijking een veelvoud is van de eerste (2x + 4y = 2 * (x + 2y)), is de rechterzijde dat niet (8 != 2 * 3).")
print("Dit betekent dat de twee vergelijkingen parallelle lijnen beschrijven die nooit snijden, waardoor er geen gemeenschappelijk punt is dat aan beide vergelijkingen voldoet.")
print("Een determinant van 0 bevestigt dat de matrix singulier is, wat kan leiden tot geen oplossing of oneindig veel oplossingen.")

try:
    x_no_sol = np.linalg.solve(A_no_sol, b_no_sol)
    print(f"Oplossing: {x_no_sol}")
except np.linalg.LinAlgError as e:
    print(f"\nFout bij het oplossen van het stelsel met np.linalg.solve(): {e}")
    print("Dit bevestigt dat er geen unieke oplossing is, en in dit specifieke geval geen enkele oplossing.")

Matrix A:
[[1 2]
 [2 4]]
Vector b:
[3 8]
De determinant van A is: 0.0

Dit stelsel heeft geen oplossing. Hoewel de linkerzijde van de tweede vergelijking een veelvoud is van de eerste (2x + 4y = 2 * (x + 2y)), is de rechterzijde dat niet (8 != 2 * 3).
Dit betekent dat de twee vergelijkingen parallelle lijnen beschrijven die nooit snijden, waardoor er geen gemeenschappelijk punt is dat aan beide vergelijkingen voldoet.
Een determinant van 0 bevestigt dat de matrix singulier is, wat kan leiden tot geen oplossing of oneindig veel oplossingen.

Fout bij het oplossen van het stelsel met np.linalg.solve(): Singular matrix
Dit bevestigt dat er geen unieke oplossing is, en in dit specifieke geval geen enkele oplossing.


---

## Oefening 3: De Inverse Berekenen


### Opdracht 3a

Bereken de inverse van de volgende 2×2 matrix met de hand (gebruik de formule) en verifieer met NumPy:

```
A = [[4, 7],
     [2, 6]]
```

Formule: A⁻¹ = (1/det(A)) × [[d, -b], [-c, a]] voor A = [[a, b], [c, d]]

In [14]:
# Jouw code voor opdracht 3a:

# 2×2 inverse met de hand berekenen
A = np.array([[4, 7],
              [2, 6]])

a, b = A[0, 0], A[0, 1]
c, d = A[1, 0], A[1, 1]

# Determinant
det = a*d - b*c

# Inverse volgens formule
A_inv_manual = (1 / det) * np.array([[d, -b],
                                      [-c, a]])

print(f"Matrix A:")
print(A)
print()
print(f"Determinant: ad - bc = {a}×{d} - {b}×{c} = {det}")
print()
print("Inverse (handmatig):")
print(A_inv_manual)
print()
print("Inverse (NumPy):")
print(np.linalg.inv(A))
print()
print(f"Gelijk? {np.allclose(A_inv_manual, np.linalg.inv(A))}")

Matrix A:
[[4 7]
 [2 6]]

Determinant: ad - bc = 4×6 - 7×2 = 10

Inverse (handmatig):
[[ 0.6 -0.7]
 [-0.2  0.4]]

Inverse (NumPy):
[[ 0.6 -0.7]
 [-0.2  0.4]]

Gelijk? True


### Opdracht 3b

Verifieer dat A @ A⁻¹ = I en A⁻¹ @ A = I voor de matrix uit 3a.

In [15]:
# Jouw code voor opdracht 3b:

# Gebruik de eerder berekende A en A_inv_manual
A = np.array([[4, 7],
              [2, 6]])
det = np.linalg.det(A)
A_inv_manual = (1 / det) * np.array([[6, -7],
                                      [-2, 4]])

identity_matrix = np.identity(2)

print("Verificatie A @ A⁻¹ = I:")
product1 = A @ A_inv_manual
print(f"A @ A⁻¹ = \n{product1}")
print(f"Is gelijk aan identiteitsmatrix? {np.allclose(product1, identity_matrix)}")

print("\nVerificatie A⁻¹ @ A = I:")
product2 = A_inv_manual @ A
print(f"A⁻¹ @ A = \n{product2}")
print(f"Is gelijk aan identiteitsmatrix? {np.allclose(product2, identity_matrix)}")

Verificatie A @ A⁻¹ = I:
A @ A⁻¹ = 
[[1. 0.]
 [0. 1.]]
Is gelijk aan identiteitsmatrix? True

Verificatie A⁻¹ @ A = I:
A⁻¹ @ A = 
[[1. 0.]
 [0. 1.]]
Is gelijk aan identiteitsmatrix? True


### Opdracht 3c

Bereken de inverse van een 3×3 matrix met NumPy en verifieer:

```
B = [[1, 2, 3],
     [0, 1, 4],
     [5, 6, 0]]
```

In [16]:
# Jouw code voor opdracht 3c:

# 3×3 matrix
B = np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])

print(f"Matrix B:\n{B}")

# Bereken de inverse met NumPy
B_inv_numpy = np.linalg.inv(B)
print(f"\nInverse van B (NumPy):\n{B_inv_numpy}")

# Verifieer dat B @ B_inv = I
identity_matrix_3x3 = np.identity(3)
product = B @ B_inv_numpy

print(f"\nVerificatie B @ B_inv = I:\n{product}")
print(f"Is gelijk aan identiteitsmatrix? {np.allclose(product, identity_matrix_3x3)}")


Matrix B:
[[1 2 3]
 [0 1 4]
 [5 6 0]]

Inverse van B (NumPy):
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]

Verificatie B @ B_inv = I:
[[ 1. -0.  0.]
 [ 0.  1.  0.]
 [ 0. -0.  1.]]
Is gelijk aan identiteitsmatrix? True


### Opdracht 3d

Gebruik de inverse om het stelsel Ax = b op te lossen via x = A⁻¹b:

```
A = [[4, 7],
     [2, 6]]
b = [5, 3]
```

Vergelijk met de oplossing via `np.linalg.solve()`.

In [17]:
# Jouw code voor opdracht 3d:

A = np.array([[4, 7],
              [2, 6]])
b = np.array([5, 3])

print(f"Matrix A:\n{A}")
print(f"Vector b: {b}")

# Oplossing via de inverse matrix: x = A⁻¹b
A_inv = np.linalg.inv(A)
x_inv = A_inv @ b
print(f"\nOplossing via inverse matrix (x = A⁻¹b): {x_inv}")

# Oplossing via np.linalg.solve()
x_solve = np.linalg.solve(A, b)
print(f"Oplossing via np.linalg.solve():     {x_solve}")

# Vergelijking van de resultaten
print(f"\nZijn de oplossingen gelijk? {np.allclose(x_inv, x_solve)}")

Matrix A:
[[4 7]
 [2 6]]
Vector b: [5 3]

Oplossing via inverse matrix (x = A⁻¹b): [0.9 0.2]
Oplossing via np.linalg.solve():     [0.9 0.2]

Zijn de oplossingen gelijk? True


---

## Oefening 4: Determinanten


### Opdracht 4a

Bereken de determinant van de volgende matrices met de hand en verifieer met NumPy:

```
A = [[3, 8],      B = [[1, 2],      C = [[2, 4],
     [4, 6]]           [3, 4]]           [1, 2]]
```

In [ ]:
# Jouw code voor opdracht 4a:



### Opdracht 4b

Bepaal welke van de matrices uit 4a inverteerbaar zijn op basis van hun determinant. Verifieer door te proberen de inverse te berekenen.

In [ ]:
# Jouw code voor opdracht 4b:



### Opdracht 4c

Verifieer de volgende eigenschappen van determinanten:

1. det(A × B) = det(A) × det(B)
2. det(Aᵀ) = det(A)
3. det(c × A) = cⁿ × det(A) voor een n×n matrix

Gebruik willekeurige 3×3 matrices en c = 2.

In [ ]:
# Jouw code voor opdracht 4c:



---

## Oefening 5: Lineaire Regressie from Scratch


### Opdracht 5a

Gegeven de volgende data, implementeer lineaire regressie via de normal equations:

```python
x_data = np.array([1, 2, 3, 4, 5])
y_data = np.array([2.1, 3.9, 6.2, 7.8, 10.1])
```

Stappen:
1. Maak de design matrix X met een kolom van enen en een kolom met x_data
2. Bereken XᵀX en Xᵀy
3. Los op voor w = [intercept, slope]
4. Visualiseer de data en de fit

In [ ]:
x_data = np.array([1, 2, 3, 4, 5])
y_data = np.array([2.1, 3.9, 6.2, 7.8, 10.1])

# Jouw code voor opdracht 5a:



### Opdracht 5b

Vergelijk je resultaat met `sklearn.linear_model.LinearRegression`.

In [ ]:
from sklearn.linear_model import LinearRegression

# Jouw code voor opdracht 5b:



---

## Klaar!

Je hebt de labo-oefeningen van les 4 afgerond. Dit was de laatste les van het lineaire algebra blok!

In de volgende les beginnen we met calculus: afgeleiden, de kettingregel, en hoe neurale netwerken leren via gradient descent.
